### ISSUE TITLE
请问你这小程序后端开源了没？

### ISSUE THREAD

**Issue by Hoke** [ximolang/mp-jishengji#1]

**Comment by seymoe** [comment]
@Hoke 嗨，后端还没开始做

**Comment by xcyxiner** [comment]
@ximolang 需要我来提供后端接口么？593091948@qq.com

**Comment by ghost** [comment]
@xcyxiner   你要是感兴趣的话,可以提供下  目前我把这项目 fork 了,练练小程序

**Comment by britreasurePerson** [comment]
@jessie-zly 如果只考虑接口，Leancloud 算是一种解决办法。还有就是用node.js 或者php等来提供restfulapi来调用了。按照后端API提供来说，需要协商接口的数据格式(或者模型类定义).

**Comment by xcyxiner** [comment]
@jessie-zly 举个例子来说，以loopback来说

```
保存数据

http POST
接口地址  http://apiserver:port/api/testabc
提交参数

{
"name":"abc",
"content":"test"
}

响应结果

http status 200

{
 "id":"123123123",
"name":"abc",
"content":"test"
}
```

接口里面重要的是数据定义，当然在 常见的 get，post，put,delete 之外的就得自定义方法写了。

**Comment by seymoe** [comment]
欢迎小伙伴们fork创造出自己的版本，如果上线请告知，我一定立马体验！
